---
name: Molecule Test
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        ansible: ["2.10", "latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt remove ansible
          sudo apt install tox
      - name: Test with molecule using tox
        run: |
          sudo -H -E tox -e ansible-${{ matrix.ansible }}
